Add endpoint for strategic action updates
uktrade/defend-data-capture pull request #10
Opened 2021-02-15 11:38 UTC by mforner13

This PR adds an API endpoint `strategic-action-updates` to perform CRUD operations on the `StrategicActionUpdate` model. It allows two filters which can be applied to get requests:

- Filtering by `strategic_action_id`, which will get all updates related to a strategic action
- Filtering by `is_submitted`, which when true will only return updates with a status of `submitted`, and when false will return updates with a status of either `in_progress` or `completed`. This distinction is to allow users to update non-submitted updates.

2021-02-15 13:58 UTC, ambrozic requested changes

2021-02-15 13:58 UTC, ambrozic commented on api/api/supply_chain_update/test/test_views.py
> +        ("strategic-action-update-list"),
parentheses around this strings above are redundant

2021-02-15 13:58 UTC, ambrozic commented on api/api/supply_chain_update/views.py
> +            is_submitted = eval(is_submitted.title())
we should not be using `eval` in production. [eval executes code](https://docs.python.org/3/library/functions.html?highlight=eval#eval). lets find better way to evaluate query strings for boolean values.

2021-02-15 14:10 UTC, mforner13 commented on api/api/supply_chain_update/views.py
> +            is_submitted = eval(is_submitted.title())
Ahhh I didn't know that, thanks for spotting! Will look into other ways :)

2021-02-15 17:43 UTC, mforner13 commented on api/api/supply_chain_update/views.py
> +            is_submitted = eval(is_submitted.title())
Updated to use `strtobool` :) Has allowed the logic to be simplified too! Let us know what you think.

2021-02-16 08:14 UTC, ambrozic approved these changes

2021-02-16 11:25 UTC, merged