Add email_domains field to GovDepartment model
uktrade/defend-data-capture pull request #13
Opened 2021-02-24 10:57 UTC by mforner13

This PR adds a field `email_domains` to the Govdepartment model. This field will hold a list of email domains linked to this government department, and will be used to determine what government department a user belongs to when creating a user object from an sso profile.

The PR also includes squashing previous commits and updating fixtures to contain `email_domains`.

2021-02-24 11:39 UTC, ambrozic approved these changes

2021-02-24 11:43 UTC, ambrozic commented
You could add more than a single email to _email_domains_ in factories and fixtures to make it a bit more realistic.

2021-02-24 16:03 UTC, tomkingston approved these changes

2021-02-25 14:09 UTC, ambrozic requested changes

2021-02-25 14:09 UTC, ambrozic commented on api/api/accounts/models.py
> +        if GovDepartment.objects.filter(email_domains__contains=[email]):
This needs case sensitive filter. I would also prefer if all emails were saved in lower case and this functionality was tested.

2021-02-25 14:23 UTC, tomkingston approved these changes

2021-02-25 14:23 UTC, tomkingston commented on api/api/accounts/models.py
> +        super(GovDepartment, self).save(*args, **kwargs)
I do see the need for this here.... however, it will mean that `clean_fields` will be called twice whenever you update the GovDepartment through a ModelForm for example (once as part of the ModelForm validation and once in the save method). 
There probably aren't any significant issues with running it twice, but I think that it might be better to run the validation in the code that is creating / updating the gov department.

2021-02-25 14:23 UTC, tomkingston commented on api/api/accounts/models.py
> +            )
Note that if more than one of the email domains already exist, you will only raise the validation error for the first one.

2021-02-25 14:53 UTC, ambrozic approved these changes

2021-02-26 09:22 UTC, mforner13 commented on api/api/accounts/models.py
> +        super(GovDepartment, self).save(*args, **kwargs)
Good point Tom! As for MVP government departments will only be added via django admin, we will add in this validation when we build the ModelForm for django admin in a few weeks.

2021-02-26 09:22 UTC, mforner13 commented on api/api/accounts/models.py
> +            )
Good point! We will add this in when adding the validation to the ModelForm :)

2021-02-26 10:09 UTC, merged