Add strategic action summary page
uktrade/defend-data-capture pull request #34
Opened 2021-04-23 15:57 UTC by mforner13

This PR adds the 'Strategic action summary page', which displays details of all the active (i.e un-archived) strategic actions linked to a given supply chain. [Design here](https://xd.adobe.com/view/9a58e0ae-80ef-48cb-88b2-150c67f2b659-cf0b/screen/1da20235-b93f-4438-a343-f49d2a8f9939)

**User flow**

- User visits `/supply-chain/strategic-actions`
- User sees a paginated list of all unarchived strategic actions for that supply chain
- User can see details of a strategic action by clicking either the action name or the + symbol
- (Not covered in this PR) User can click the 'change' link next to a field and update that piece of information

**Also included**

This PR also includes:
- The abstraction of the pagination component into an 'includes' template which will avoid the repetition of the component's html
- The addition of a breadcrumbs block in `base.html`. If there are no breadcrumbs passed in, nothing will be rendered in this block.
- A mixin `GovDepPermissionMixin` which checks that the current user has the same gov department as the supply chain in the url, and returns a 403 forbidden page if not (custom template for this page to come after design is done). This doesn't actually use Django's permissions module, so any feedback on whether this is an appropriate way to do it would be v appreciated!

2021-04-26 11:08 UTC, NickFitz commented on defend_data_capture/supply_chains/test/test_utils.py
> +    when
When indeed? ;-)

2021-04-26 11:15 UTC, NickFitz approved these changes
Seems OK to me 👍

2021-04-26 11:30 UTC, mforner13 commented on defend_data_capture/supply_chains/test/test_utils.py
> +    when
Fixed 😋

2021-04-26 15:47 UTC, dev-digital requested changes
Added some comments

2021-04-26 15:47 UTC, dev-digital commented on defend_data_capture/supply_chains/utils.py
> +    """
Minor or FYI

While writing docstrings its better to stick to [PEP](https://www.python.org/dev/peps/pep-0257/#multi-line-docstrings) convention for multi-lines.
Now its fine, would not matter. When we try to publish docs to [gh-pages](https://pages.github.com/) by using tools like [Sphnix](https://www.sphinx-doc.org/en/master/) we could run into some formatting issues.

2021-04-26 15:47 UTC, dev-digital commented on defend_data_capture/supply_chains/utils.py
> +        # Update to slug once tasklist PR is merged
Can we remove this now.

2021-04-26 15:47 UTC, dev-digital commented on defend_data_capture/supply_chains/utils.py
> +            self.supply_chain = None
Though its unlikely to hit this line, but it would result in server 5xx error on line 63 as you try to de-reference from None.

With this being a Mixin, I would not have touched(write into) _self.supply_chain_ irrespective of what this helper trying to accomplish.

I would have refactored __get_supply_chain_from_url_ to return a bool based on the check.

2021-04-26 15:47 UTC, dev-digital commented on defend_data_capture/supply_chains/views.py
> +    template_name = "strategic-action-summary.html"
Can we have python casing for files, please ?

_strategic_action_summary.html_

2021-04-26 15:47 UTC, dev-digital commented on defend_data_capture/supply_chains/test/factories.py
> +    name = factory.Sequence(lambda n: f"Product {n}")
Just curious, why was this required ?

2021-04-26 15:47 UTC, dev-digital commented on cypress/integration/strategic_action_summary_spec.js
> +  })
This is not required anymore

2021-04-26 15:47 UTC, dev-digital commented on cypress/integration/strategic_action_summary_spec.js
> +describe('The strategic action summary page', () => {
Quite inclusive testing :+1:

2021-04-26 15:47 UTC, dev-digital commented on defend_data_capture/supply_chains/templates/strategic-action-summary.html
> +    <div id="accordion-section-content-{{ action.name|slugify }}" class="govuk-accordion__section-content" aria-labelledby="accordion-section-heading-{{ action.name|slugify }}">
Optional:
Not sure if it adds any value to break up the markup for the contents of action into a separate include but it will certainly help reduce the length of this template

2021-04-26 15:55 UTC, mforner13 commented on defend_data_capture/supply_chains/templates/strategic-action-summary.html
> +<p class="govuk-body">Select a strategic action to edit details.</p>
Ah good catch! On [this page in the design](https://xd.adobe.com/view/9a58e0ae-80ef-48cb-88b2-150c67f2b659-cf0b/screen/c18ccd03-792a-4737-a896-7b34bb630418) it still shows the old text :)

2021-04-26 15:58 UTC, mforner13 commented on defend_data_capture/supply_chains/templates/strategic-action-summary.html
> +<h1 class="govuk-heading-xl">Strategic actions for {{ supply_chain.name }}</h1>
I think good idea!

2021-04-26 16:00 UTC, mforner13 commented on defend_data_capture/supply_chains/templates/strategic-action-summary.html
> +        {{ action.description|truncatechars_html:150 }}
Ah no, I had misread the html variant's description on the docs! Have removed.

2021-04-26 16:08 UTC, mforner13 commented on defend_data_capture/supply_chains/templates/strategic-action-summary.html
> +              {{ action.get_category_display|default:"No information" }}
Here in the docs: https://docs.djangoproject.com/en/3.2/ref/models/instances/#django.db.models.Model.get_FOO_display .

Was hard to track down though! Doesn't easily come up in google

2021-04-26 16:14 UTC, mforner13 commented on defend_data_capture/assets/stylesheets/application.scss
> +}
Ah great find! Thanks 😄

2021-04-26 16:25 UTC, mforner13 commented on defend_data_capture/supply_chains/test/factories.py
> +    name = factory.Sequence(lambda n: f"Product {n}")
So without it, when supply chains were made made within the same test session, they would all have the same slug, so when a url with a slug in was called, it wouldn't know which supply chain to get as there were multiple in the test database with the same slug.

2021-04-27 08:22 UTC, dev-digital commented on defend_data_capture/supply_chains/test/factories.py
> +    name = factory.Sequence(lambda n: f"Product {n}")
Yes, it would be very handy :+1:

2021-04-27 09:12 UTC, mforner13 commented on defend_data_capture/supply_chains/templates/strategic-action-summary.html
> +              Does the strategic action apply UK-wide or in England only?
Have checked with Sally & Baris and they're happy with this updated wording as the 'in' makes it correct :)

2021-04-27 09:16 UTC, mforner13 commented on defend_data_capture/supply_chains/templates/strategic-action-summary.html
> +              Does this action affect the whole supply chain or a subset or supply chains?
Spoke to Sally/Baris about this, and Sally suggested it should actually be `Does this action affect the whole supply chain or a section of supply chains?` - have updated :)

2021-04-27 10:25 UTC, mforner13 commented on defend_data_capture/supply_chains/utils.py
> +            self.supply_chain = None
Good point Prashanth! I've refactored the mixin [in this commit](https://github.com/uktrade/defend-data-capture/pull/34/commits/269be62b30febdb90a86b78c56d415124e113ddf) and hopefully simplified the logic :)

2021-04-27 10:37 UTC, mforner13 commented on defend_data_capture/supply_chains/templates/strategic-action-summary.html
> +    <div id="accordion-section-content-{{ action.name|slugify }}" class="govuk-accordion__section-content" aria-labelledby="accordion-section-heading-{{ action.name|slugify }}">
Ah so I did try to abstract the table out into an include, but because the text displayed as the field headings aren't on the models, and due to the pagination, it made it pretty overcomplicated to create a reusable table. Have you had any luck with it in the key information template?

2021-04-27 10:44 UTC, mforner13 commented on defend_data_capture/supply_chains/utils.py
> +    """
Thanks! Have updated the docstrings to be in line with PEP :)

2021-04-27 11:12 UTC, dev-digital commented on defend_data_capture/supply_chains/templates/strategic-action-summary.html
> +    <div id="accordion-section-content-{{ action.name|slugify }}" class="govuk-accordion__section-content" aria-labelledby="accordion-section-heading-{{ action.name|slugify }}">
Oh, ok. thats fine.

Yes, I created sub-template for accordion content.

2021-04-27 11:21 UTC, dev-digital approved these changes
:+1:

2021-04-27 11:21 UTC, dev-digital commented on defend_data_capture/supply_chains/test/test_views.py
> +    page for that supply chain."""
You didn't have to change the existing ones but its nice you did it.
For the next time, closing tags are always on new-line

![image](https://user-images.githubusercontent.com/81681068/116232967-ac9c1880-a752-11eb-9bc6-27654d41114a.png)

2021-04-27 11:24 UTC, dev-digital commented on defend_data_capture/supply_chains/templates/strategic-action-summary.html
> +              Does the strategic action apply UK-wide or in England only?
Yes, thats true it needed update in design.

2021-04-27 12:33 UTC, merged