Make breadcrumbs consistent across pages
uktrade/defend-data-capture pull request #40
Opened 2021-04-29 16:13 UTC by mforner13

This PR makes the breadcrumbs structure on the existing pages consistent.

It also:
- updates all tests to check the links of breadcrumbs
- adds the `aria-current="page"` attribute to final breadcrumbs
- makes all final breadcrumbs link to the url of the page, rather than `#`.

**Breadcrumb structure:**
Home(index) > [Supply chain name](task list) > ...

The breadcrumbs of existing pages are now as follows:

- Task list
![Screenshot 2021-04-29 at 17 07 07](https://user-images.githubusercontent.com/22460823/116582491-57f0cd00-a90d-11eb-8715-9918744ea7c1.png)

- Complete page (after submitting update for a supply chain)
![Screenshot 2021-04-29 at 17 10 04](https://user-images.githubusercontent.com/22460823/116582946-c0d84500-a90d-11eb-86ec-9f648de30651.png)

- Strategic action summary page
![Screenshot 2021-04-29 at 17 09 00](https://user-images.githubusercontent.com/22460823/116582781-9ab2a500-a90d-11eb-867d-06928bfddec0.png)

- Supply chain summary page
![Screenshot 2021-04-29 at 17 08 44](https://user-images.githubusercontent.com/22460823/116582742-9090a680-a90d-11eb-8063-a60da6564d7c.png)

2021-04-29 16:28 UTC, NickFitz approved these changes
👍

2021-04-30 07:52 UTC, dev-digital requested changes
Minor change requested w/o approval.

2021-04-30 07:52 UTC, dev-digital commented on defend_data_capture/supply_chains/templates/sc_summary.html
> +        <a class="govuk-breadcrumbs__link" href="{% url 'sc_summary' sc_slug=supply_chain.slug %}">Full details of {{ supply_chain.name }}</a>
Don't we need _aria-current="page"_ here ?

2021-04-30 07:52 UTC, dev-digital commented on defend_data_capture/supply_chains/templates/sc_summary.html
> +        <a class="govuk-breadcrumbs__link" href="{% url 'tlist' sc_slug=supply_chain.slug %}">{{ supply_chain.name }}</a>
Just curious if its a cosmetic change or feature was broken before ?

2021-04-30 08:20 UTC, mforner13 commented on defend_data_capture/supply_chains/templates/sc_summary.html
> +        <a class="govuk-breadcrumbs__link" href="{% url 'sc_summary' sc_slug=supply_chain.slug %}">Full details of {{ supply_chain.name }}</a>
Thanks for spotting! Have updated and pushed :)

2021-04-30 08:25 UTC, mforner13 commented on defend_data_capture/supply_chains/templates/sc_summary.html
> +        <a class="govuk-breadcrumbs__link" href="{% url 'tlist' sc_slug=supply_chain.slug %}">{{ supply_chain.name }}</a>
Just cosmetic - looking around at lots of examples + Nick's work I think the standard is to have the href in quotes even if it's a URL tag. I looked round the django docs and couldn't find them saying it specifically though, just [this example](https://docs.djangoproject.com/en/3.2/howto/custom-template-tags/#inclusion-tags): 
![image](https://user-images.githubusercontent.com/22460823/116669012-f6c10c00-a995-11eb-82d7-885a4725b3e8.png)

2021-04-30 08:27 UTC, dev-digital approved these changes
:+1:

2021-04-30 10:01 UTC, merged